import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/layout/Navbar';
import ThemeRegistry from '@/ThemeRegistry';
import Footer from '@/components/layout/Footer';
import { Box } from '@mui/material';
import Banner from '@/components/layout/Banner';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Vietchill - Ứng dụng đặt phòng khách sạn',
	description: 'Generated by Vietchill - Ứng dụng đặt phòng khách sạn',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head>
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link
					rel='preconnect'
					href='https://fonts.gstatic.com'
					crossOrigin='anonymous'
				/>
				<link
					rel='stylesheet'
					href='https://fonts.googleapis.com/icon?family=Material+Icons'
				/>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} `}
				style={{ height: '100vh' }}>
				<ThemeRegistry>
					<Navbar />
					<main>
						<Banner />
						<Box className='min-h-screen max-w-7xl mx-auto p-6'>
							{children}
						</Box>
					</main>
					<Footer />
				</ThemeRegistry>
			</body>
		</html>
	);
}
