import EmotionRegistry from '@/EmotionRegistry';
import { AuthProvider } from '@/features/auth/AuthContext';
import ThemeRegistry from '@/ThemeRegistry';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { Inter, Playfair_Display } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const playfair = Playfair_Display({
	subsets: ['latin'],
	variable: '--font-playfair',
});

export const metadata: Metadata = {
	title: 'VietStay - Ứng dụng đặt phòng khách sạn',
	description: 'Generated by VietStay - Ứng dụng đặt phòng khách sạn',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head>
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link
					rel='preconnect'
					href='https://fonts.gstatic.com'
					crossOrigin='anonymous'
				/>
				<link
					rel='stylesheet'
					href='https://fonts.googleapis.com/icon?family=Material+Icons'
				/>
			</head>
			<body
				id='root'
				className={`${inter.variable} ${playfair.variable}`}
				style={{ height: '100vh' }}>
				<EmotionRegistry>
					<AppRouterCacheProvider options={{ enableCssLayer: true }}>
						<ThemeRegistry>
							<AuthProvider>{children}</AuthProvider>
						</ThemeRegistry>
					</AppRouterCacheProvider>
				</EmotionRegistry>
			</body>
		</html>
	);
}
