import Footer from '@/features/common/layout/Footer/Footer';
import Navbar from '@/features/common/layout/Navbar/Navbar';
import EmotionRegistry from '@/EmotionRegistry';
import ThemeRegistry from '@/ThemeRegistry';
import { Box } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { Inter, Playfair_Display } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/features/auth/AuthContext';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const playfair = Playfair_Display({
	subsets: ['latin'],
	variable: '--font-playfair',
});

export const metadata: Metadata = {
	title: 'VietStay - Ứng dụng đặt phòng khách sạn',
	description: 'Generated by VietStay - Ứng dụng đặt phòng khách sạn',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head>
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link
					rel='preconnect'
					href='https://fonts.gstatic.com'
					crossOrigin='anonymous'
				/>
				<link
					rel='stylesheet'
					href='https://fonts.googleapis.com/icon?family=Material+Icons'
				/>
			</head>
			<body
				id='root'
				className={`${inter.variable} ${playfair.variable}`}
				style={{ height: '100vh' }}>
				<EmotionRegistry>
					<AppRouterCacheProvider options={{ enableCssLayer: true }}>
						<ThemeRegistry>
							<AuthProvider>
								<Navbar />
								<main>
									<Box className='min-h-[70vh]'>
										{children}
									</Box>
								</main>
								<Footer />
							</AuthProvider>
						</ThemeRegistry>
					</AppRouterCacheProvider>
				</EmotionRegistry>
			</body>
		</html>
	);
}
