import Footer from '@/features/shared/components/layout/Footer/Footer';
import Navbar from '@/features/shared/components/layout/Navbar/Navbar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'VietStay - Ứng dụng đặt phòng khách sạn',
  description: 'Generated by VietStay - Ứng dụng đặt phòng khách sạn',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <main className='pt-12'>{children}</main>
      <Footer />
    </>
  );
}
