// lib/data.ts

import { RoomType } from '@/types/room';

const ROOM_DATA: { success: boolean; message: string; data: RoomType } = {
	success: true,
	message: 'Room type retrieved successfully',
	data: {
		id: 1,
		name: 'Phòng Deluxe',
		area: 30,
		price: 1000000,
		quantity: 10,
		adult: 2,
		children: 0,
		description:
			'Phòng Deluxe với diện tích 30m2, phù hợp cho gia đình hoặc nhóm bạn bè.',
		created_at: '2024-11-29T00:00:00.000000Z',
		updated_at: '2024-11-29T00:00:00.000000Z',
		images: [
			{
				id: 1,
				room_type_id: 1,
				path: '/images/room-1.jpg',
				is_thumbnail: true,
				created_at: '2025-08-14 20:40:34',
			},
			{
				id: 2,
				room_type_id: 1,
				path: '/images/room-2.jpg',
				is_thumbnail: false,
				created_at: '2025-08-14 20:40:34',
			},
			{
				id: 3,
				room_type_id: 1,
				path: '/images/room-3.jpg',
				is_thumbnail: false,
				created_at: '2025-08-14 20:40:34',
			},
		],
		facilities: [
			{
				id: 1,
				name: 'wifi',
				content: 'Wi-Fi',
				description: 'Kết nối Internet...',
				pivot: { room_type_id: 1, facility_id: 1 },
			},
			{
				id: 2,
				name: 'conditioner',
				content: 'Máy Lạnh',
				description: 'Hệ thống điều hòa...',
				pivot: { room_type_id: 1, facility_id: 2 },
			},
			{
				id: 3,
				name: 'tv',
				content: 'Truyền Hình',
				description: 'TV màn hình phẳng...',
				pivot: { room_type_id: 1, facility_id: 3 },
			},
			{
				id: 4,
				name: 'desk',
				content: 'Bàn làm việc',
				description: 'Trang bị bàn làm việc...',
				pivot: { room_type_id: 1, facility_id: 4 },
			},
			{
				id: 5,
				name: 'heater',
				content: 'Máy Sưởi',
				description: 'Hệ thống sưởi ấm...',
				pivot: { room_type_id: 1, facility_id: 5 },
			},
			{
				id: 6,
				name: 'water-heater',
				content: 'Máy Nước Nóng',
				description: 'Máy nước nóng...',
				pivot: { room_type_id: 1, facility_id: 6 },
			},
			{
				id: 7,
				name: 'safe',
				content: 'Két sắt',
				description: 'Két sắt điện tử...',
				pivot: { room_type_id: 1, facility_id: 7 },
			},
			{
				id: 8,
				name: 'fridge',
				content: 'Tủ lạnh',
				description: 'Tủ lạnh mini...',
				pivot: { room_type_id: 1, facility_id: 8 },
			},
			{
				id: 9,
				name: 'kettle',
				content: 'Bình siêu tốc',
				description: 'Bình đun siêu tốc...',
				pivot: { room_type_id: 1, facility_id: 9 },
			},
			{
				id: 10,
				name: 'minibar',
				content: 'Minibar',
				description: 'Minibar với thức uống...',
				pivot: { room_type_id: 1, facility_id: 10 },
			},
		],
		features: [
			{
				id: 1,
				name: 'bedroom',
				content: 'Phòng ngủ',
				pivot: { room_type_id: 1, feature_id: 1 },
			},
			{
				id: 2,
				name: 'balcony',
				content: 'Ban công',
				pivot: { room_type_id: 1, feature_id: 2 },
			},
			{
				id: 3,
				name: 'kitchen',
				content: 'Nhà bếp',
				pivot: { room_type_id: 1, feature_id: 3 },
			},
			{
				id: 4,
				name: 'garden-view',
				content: 'Hướng sân vườn',
				pivot: { room_type_id: 1, feature_id: 4 },
			},
			{
				id: 5,
				name: 'lake-view',
				content: 'Hướng hồ',
				pivot: { room_type_id: 1, feature_id: 5 },
			},
			{
				id: 6,
				name: 'forest-view',
				content: 'Hướng rừng thông',
				pivot: { room_type_id: 1, feature_id: 6 },
			},
			{
				id: 7,
				name: 'city-view',
				content: 'Hướng thành phố',
				pivot: { room_type_id: 1, feature_id: 7 },
			},
			{
				id: 8,
				name: 'single-bed',
				content: 'Giường đơn',
				pivot: { room_type_id: 1, feature_id: 8 },
			},
			{
				id: 9,
				name: 'double-bed',
				content: 'Giường đôi',
				pivot: { room_type_id: 1, feature_id: 9 },
			},
			{
				id: 10,
				name: 'Interconnecting-room',
				content: 'Phòng thông nhau',
				pivot: { room_type_id: 1, feature_id: 10 },
			},
		],
	},
};
